# Generated by Django 3.2 on 2021-04-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coclisim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.IntegerField(default=20)),
                ('TR', models.IntegerField(default=22)),
                ('RH', models.IntegerField(default=50)),
                ('VEL', models.FloatField(default=0.1)),
                ('CLO', models.IntegerField(default=1)),
                ('MET', models.FloatField(default=1.3)),
                ('PA', models.IntegerField(default=0)),
                ('WME', models.IntegerField(default=0)),
            ],
        ),
    ]
