# Generated by Django 3.2 on 2021-04-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coclisim', '0004_remove_calcclass_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcclass',
            name='CLO',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='calcclass',
            name='PA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calcclass',
            name='RH',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='calcclass',
            name='TA',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='calcclass',
            name='TR',
            field=models.FloatField(default=22),
        ),
        migrations.AlterField(
            model_name='calcclass',
            name='WME',
            field=models.FloatField(default=0),
        ),
    ]
