# Generated by Django 3.2 on 2021-04-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coclisim', '0005_auto_20210423_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalcClass',
        ),
    ]
